version: '3.1'

services:
  postgres:
    image: postgres:13-alpine
    container_name: test-postgres1
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "8181:5432"